### ISSUE TITLE
Should non-db errors pass-through when using `return` option?

### ISSUE THREAD

**Issue by devinivy** [PixulHQ/avocat#2]
I have an onPreResponse handler that is intended to map then reformat some errors.  Not all the errors are DB errors.  I see that `Avocat.rethrow(error, { return: true })` returns `false` in this case rather than my `error`, and I'm just ensuring that this is expected behavior.  You can see the current usage here: https://github.com/devinivy/hapipal-realworld-example-app/blob/master/lib/extensions/error.js#L54-L56.  And of course, thanks for avocat!  It's working great 👌

**Comment by devinivy** [comment]
At a glance it seems that bounce returns `undefined` in this case, which is in a similar spirit to avocat's current functionality 👍

https://github.com/hapijs/bounce/blob/6a6abfbd9e6025103f0f34c1c36a06a4b0bd6eb1/lib/index.js#L46-L48

**Comment by optii** [comment]
What would be the behaviour you expect/wish in this case ? I would be open to changing this to ,`undefinded` if it seems more coherent with boom and other error handling. Or if you expected something else in the case of it not being a db error im open to discus and see if there is something that can be done !

And thanks for the feedback!

**Comment by devinivy** [comment]
Originally I naively expected it to pass-through my error when it was a non-DB error, but instead it was returning `false`.  For example:
```js
    // How I expected to use avocat for error transformation in onPreResponse
    return Avocat.rethrow(error, { return: true });

    // How to actually use avocat for this
    return Avocat.rethrow(error, { return: true }) || error;
```

Now I see that it is very similar behavior to bounce, which I think is a good thing, so I would not suggest any changes.  As a very minor detail, perhaps it could return `undefined` rather than `false`, as you mentioned.  Thanks!
