### ISSUE TITLE
Any interest in joining hapi pal?

### ISSUE THREAD

**Issue by devinivy** [PixulHQ/avocat#4]
I am wondering if you would be interested in incorporating this module into the [pal ecosystem](https://github.com/hapipal).  I think this is a really important module when using hapi and objection together, and of course pal supports that integration with the schwifty plugin.  This module already uses the same conventions and has the same license, so the transition would be straightforward.  Under pal @optii would remain the lead maintainer.  If Pixul sponsors the development of the module, I see no reason why that couldn't be noted in the readme.  Avocat docs would go up on https://hapipal.com and if we either add an API.md file or make some adjustments to hpal, its documentation could also be searchable using `hpal docs`.  Overall I think it could be a great fit, but of course no problem either way!  I would be happy to clarify anything about how this would work, including how pal module maintainership works, but I bet you're already fairly familiar :)

**Comment by optii** [comment]
This sounds like a good thing, and at the moment don't see why we shouldn't make that move. Would love to chat a bit about getting this over there and what would be required to make sure it fits in the hapipal ecosystem. I/(we) haven't got much time at the moment, finalizing a big project, but I'm sure we can figure out a way to get the ball rolling on this. Drop me PM on the hapi slack when your around and we can discuss further
